#!/bin/bash

## Created By Aditya Shakya

#MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -3 -yoffset -968 -width 5 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -theme solarized -font "tewi 8"<<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) physlock ;;
                *Logout) bspc quit && killall bash;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
